### ISSUE TITLE
Fatal error twig

### ISSUE THREAD

**Issue by DeeJaVu** [ZingPHP/Zing#3]
hi i changed my tplEngine from Smarty to Twig, but now i get this error

> Fatal error: Class Modules\TemplateEngines\Twig\ZingTemplateLoader
> contains 1 abstract method and must therefore be declared abstract or
> implement the remaining methods (Interfaces\ZingTemplate::parseTpl) in
> /public_html/Zing/src/Modules/TemplateEngines/Twig/ZingTemplateLoader.php
> on line 52

**Comment by DeeJaVu** [comment]
i added

>     public function parseTpl($tpl, $key, $data = ""){
>             $smarty = new Smarty();
>             if(is_array($key)){
>                 foreach($key as $k => $v){
>                     $smarty->assign($k, $v);
>                 }
>             }else{
>                 $smarty->assign($key, $data);
>             }
>             $cache_id = md5($_SERVER['REQUEST_URI']);
>             return $smarty->fetch("string:$tpl", $cache_id);
>         }

and now its working

**Comment by DeeJaVu** [comment]
i added

>     public function parseTpl($tpl, $key, $data = ""){
>             $twig = new Twig();
>             if(is_array($key)){
>                 foreach($key as $k => $v){
>                     $twig->assign($k, $v);
>                 }
>             }else{
>                 $twig->assign($key, $data);
>             }
>             $cache_id = md5($_SERVER['REQUEST_URI']);
>             return $twig->fetch("string:$tpl", $cache_id);
>         }

to /Zing/src/Modules/TemplateEngines/Twig/ZingTemplateLoader.php
and now its working but i dont know if that is the correct way, because im just a beginner in php

and btw when i add {% include 'header.tpl' %} in my main.tpl it gives me 404 not found error,
same for Smarty

**Comment by TheColorRed** [comment]
I have fixed the issue, we can actually use something a little simpler than smarty:

    public function parseTpl($tpl, $data, $unUsed = ""){
        $twig = new Twig_Environment(new Twig_Loader_String());
        return $twig->render($tpl, $data);
    }

If you pull, you will get the updates.

**Comment by ghost** [comment]
Thanks
